# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countrydata.Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
